### ISSUE TITLE
Why were you fired from github?

### ISSUE THREAD

**Issue by najela** [holman/ama#705]
[I didn't find the reason in this article](http://feedproxy.google.com/~r/holman/~3/8w-OpokH0jA/fired)

**Comment by holman** [comment]
I haven't talked about it publicly yet.

**Comment by mrhead** [comment]
What about now, do you mind to share it?

**Comment by holman** [comment]
Eventually I will. I'll be sure everyone sees it.

**Comment by najela** [comment]
>I'll be sure everyone sees it.
With all the shootings happening, I guarantee some people may die waiting :)
