### ISSUE TITLE
What you think about RegExps idea?

### ISSUE THREAD

**Issue by tunnckoCore** [holman/ama#707]
That's a big idea and project, and have many steps to do more.

- [RegExps Github Organization](https://github.com/regexps)
- [meta stuff repository](https://github.com/regexps/meta)
- [General discussion and roadmap](https://github.com/regexps/meta/issues/16)
- [more big and older "first hit" discussion](https://github.com/regexps/meta/issues/2)

In general  - centralized place for regular expression world for all languages. Just we are javascripters and we start with it.

[https://github.com/tunnckoCore/ama](https://github.com/tunnckoCore/messages)

**Comment by holman** [comment]
First I'd heard of it, but it looks pretty cool. Kind of wish there was a website that presented them all better than a recently-sorted list of repositories, but I think the idea is there. I've definitely felt like I've been reinventing the wheel every time I take a crack at regexes, ha. :)

**Comment by tunnckoCore** [comment]
Yea, it's on the roadmap, just we are busy. Because of the i've write latest "general discussion" thread to summarize the previously almost considered things.

about website https://github.com/regexps/meta/issues/12#issuecomment-122036704
