### ISSUE TITLE
gitter or slack or ?

### ISSUE THREAD

**Issue by robi-y** [holman/ama#708]
(for oss project)

**Comment by holman** [comment]
For open source? Probably Gitter. I haven't really used it much, but it seemed to be better set up for handling open source and more repo-specific setups.

I wish Slack would court the open source market quite a bit more. The existing limits on history and such is fine, but it's just a pain to manage users on such a project. It'd be rad if you could pop in a chat room the same way you can pop in and browse code on GitHub. Part of this is exasperated by their complete mess of a user account system, but them's the breaks.

**Comment by sharat** [comment]
Like @holman mentioned, Gitter is definitely great for open source project but not really attractive in an organization perspective.

As a developer I find Gitter is cool. However, hardly the stake holders who are not really technical agree to it. They are kind of okay with Slack. Also, Slack is the buzz word and gained great reputation in short span of time irrespective of other cheap and feature rich products like HipChat.
