### ISSUE TITLE
What do you use for Sql explorer?

### ISSUE THREAD

**Issue by hahmed** [holman/ama#710]
What do you use on a mac for sql explorer?

On windows most people use Sql Server Management Studio, not sure what people use on a mac.

Thanks

**Comment by christian-fei** [comment]
I know [RazorSQL](http://razorsql.com/) and [MySQL Workbench](https://www.mysql.it/products/workbench/)

**Comment by holman** [comment]
Usually I'll just use the command line... either `sqlite3` or `mysql` or the Rails console. Very occasionally (usually if I'm digging into iOS or OS X sqlite files) I'll use something like SQLPro or other freebie/trial app on the AppStore, but that's really a pretty rare thing for me.

**Comment by sharat** [comment]
@hahmed If it's about Microsoft SQL Server, I use SQL Pro (From Mac AppStore)

**Comment by hahmed** [comment]
@sharat is this the same as http://www.macsqlclient.com?

**Comment by sharat** [comment]
@hahmed - Yes. They recently rebranded the product it seems.
