### ISSUE TITLE
Is GitHub comfortable handing over all their code to GitHub Enterprise customers?

### ISSUE THREAD

**Issue by ur0** [holman/ama#711]
I've noticed that pretty much all of GitHub's (the rails app) source code is available to Enterprise customers, using a form of obfuscation that is ridiculously weak. The code shares almost all features with GitHub.com and could be accessed by anyone with basic programming acumen.
My question is: is GitHub comfortable doing this?

**Comment by holman** [comment]
Probably!

I think the idea was to keep honest people honest. There's basically no way to perfectly obfuscate code (particularly not within Ruby), so it's kind of a lot of wasted cycles to spend a lot of time on this. It's way easier to sue the shit out of someone if they step out of line, anyway.

**Comment by ur0** [comment]
Thanks. So here, you guys depend on the acceptance of the license agreement
and it's enforcement. I got it.
But, do you think that any of the copies of the source would be out in the
wild? And what might one make of it?
Thanks (My curiosity is insatiable, I'm a newbie rails dev)
>
>

**Comment by holman** [comment]
> But, do you think that any of the copies of the source would be out in the wild? And what might one make of it?

It's sort of like DRM; it's easier to just say it's illegal rather than to try to build controls into your product. Once the code leaves your possession, all bets are off.

That said, :notes: *not my problem, not my worry*. :musical_note:
