### ISSUE TITLE
font rendering on your blog in firefox

### ISSUE THREAD

**Issue by Justin-Chaschowy** [holman/ama#712]
looks like this 

http://i.imgur.com/C8wM4vf.png

**Comment by holman** [comment]
Weird; looks fine to me. What version + platform?

**Comment by Justin-Chaschowy** [comment]
28.0 on linux

**Comment by holman** [comment]
Ah. I'll keep my eyes open for possible fixes, but Linux is kind of a crap shoot when it comes to font rendering. `¯\_(ツ)_/¯`

**Comment by grawity** [comment]
Firefox 40 with freetype 2.6 [seems to be working fine](https://cloud.githubusercontent.com/assets/31021/9833201/50676e3e-5997-11e5-954a-d9ff95d2effc.png) (though still not quite [as good](https://cloud.githubusercontent.com/assets/31021/9833208/75e846b0-5997-11e5-8482-7eced6522a35.png) as Chromium).
