### ISSUE TITLE
Database diagrams

### ISSUE THREAD

**Issue by gerep** [holman/ama#713]
When working on a Rails project do you use any application so you can create the database diagram or does the `schema.rb` file is enough for you?

**Comment by holman** [comment]
`schema.rb` is a lot faster for me than dealing with diagrams; I usually just end up using that.

**Comment by gerep** [comment]
Thanks for your answer.

But even when creating  new database? You can manage all relations easily with `schema.rb`?

**Comment by holman** [comment]
Not sure what you're asking necessarily- usually migrations and `schema.rb` are just fine for handling the spin up of a new db.

If I'm new to a codebase and am trying to get a better understanding of how everything works together, I'll also just look at the models and a Rails console session. I can usually get a good grasp of everything at that point.
