### ISSUE TITLE
What is zachholman.com built on?

### ISSUE THREAD

**Issue by ur0** [holman/ama#719]
Hi (back to ask another stupid question),

I was going through your blog (it's nice - you got some awesome posts up there). But, what have you built it up on? Definitely not WordPress, I'm betting Jekyll. 
Okay, that's a trade secret but hey, it looks awesome and that's what got me wondering. 

TL;DR: What CMS do you use?

**Comment by holman** [comment]
It's Jekyll! I'm a fan.
