### ISSUE TITLE
Apple upgrade program for iPhone

### ISSUE THREAD

**Issue by sharat** [holman/ama#725]
One of the Internet articles mentioned about your every year upgrade strategy for iPhone. How do you look at the Apple Upgrade Program?

https://usesthis.com/interviews/zach.holman/

Sarath

**Comment by holman** [comment]
I took a look at it and ended up with three options:

- Do the Apple replacement program. It's the cheapest option, although I was thinking of selling or loaning out my current phone and Apple's program is a trade-in. You also have to make an in-store appointment; you can't get it shipped on launch day. 
- Do T-Mobile's JUMP program. That requires a trade-in, and also requires either going into the store or talking to them on the phone. I'm in Europe atm, so both of those are difficult.
- Just pay full freight for a phone again, as usual.

I chose the last option. Wasn't sure the money saved from the replacement program was worth what could be had if I sold my 6S next year. Also I like having the phone shipped to me on launch day. Kinda nice.

**Comment by queuebit** [comment]
:+1:
