### ISSUE TITLE
Hubot Danger Room and all the other rooms

### ISSUE THREAD

**Issue by judoole** [holman/ama#727]
First, love your presentations and this QA - you are an inspiration! And your dotfiles, they are pretty swell.

Q: How would you go about if you started out introducing Hubot from scratch. Do you recommend that Hubot receive commands only in one "Danger Room" for operation tasks as deploy etc? And post information in channels like **production** when deploy has happened? But still respond to pug me in others?

**Comment by holman** [comment]
I think theoretically you could have two bots: one for "fun" stuff, and one for "real" stuff. But I think going simpler is the easier option for everyone: just have one bot that responds to everything.

One thing that's kind of nice once you reach a certain amount of traffic in a room is to split the room into two rooms. So you might have a room for your main application, but you split that into two rooms: one for discussion about the app, and one for robots talking about the app (deploy notifications, posting metrics and graphs, and so on). The latter is where you'd talk to hubot, and the former is where you talk to other humans.

Beyond that, yeah, it likely makes sense to have a "fun" room where you can talk about watercooler conversations.

**Comment by judoole** [comment]
Excellent answer. Thanks! :tada:
