### ISSUE TITLE
what program do you prefer to use to compress your scss files into css?

### ISSUE THREAD

**Issue by alohavolha** [holman/ama#729]
Hi Zack!
I am currently using prepros but it is very buggy. It is only a temporary fix as I am just learning sass but once I get better and could actually think in sass I would like to use a more efficient tool. What is your go-to tool ?
thank you

**Comment by holman** [comment]
Hey!

So for me it mostly depends on the project. If it's a Rails project I get it via the Rails Pipeline (which just uses the `sass` gem).

The other thing I might hack on would be a Jekyll site, which [now has support](http://jekyllrb.com/docs/assets/) for it baked in as well.

For vanilla sites that aren't either of those two... well, I don't have to deal with that too much. :) Usually I end up with a Ruby app, so I can just roll with the `sass` gem and not have to think about it too much. Your mileage may vary, though!
