### ISSUE TITLE
what are your thoughts on rems, ems, % and px?

### ISSUE THREAD

**Issue by alohavolha** [holman/ama#730]
what do you normally prefer to use px/%/em/rem? and why?
I was recently introduced to rem and looks like from now on I will only be using %, rem and occasionally px in my code.

oh, and what do you think about these guys ( i just came across it the other day and though it was interesting, especially the http://txti.es/about )
www.motherfuckingwebsite.com

Thank you!

**Comment by holman** [comment]
I'm probably not the best person to ask... I've fucked with rem units the last few things I've built, and they're dope, but I don't have enough cachet to really have an opinion here. :)

The txti thing looks neat, for certain use cases. Big fan of things like design, though, so might only really work in a couple smaller use cases.
