### ISSUE TITLE
github issue: github does not make good use of the screen

### ISSUE THREAD

**Issue by andreasabel** [holman/ama#734]
For example, the github issue tracker shows me max. 16 issues at a time.
![github-max-16-issues](https://cloud.githubusercontent.com/assets/1155218/10331650/3bc02eb4-6cd7-11e5-8404-c9503c55ce5f.png)
An older, unfortunately discontinued tracker gives me 38 issues and an I can configure it to give me a lot of extra information in the table.
![google-38-issues](https://cloud.githubusercontent.com/assets/1155218/10331671/6ea15c9a-6cd7-11e5-84f0-e5b01bfd910b.png)

(Did not find a better issue tracker for github.)

**Comment by holman** [comment]
support@github.com

**Comment by dideler** [comment]
@andreasabel for a different perspective, I think GitHub Issues makes good use of the screen and the older issue tracker does not. Filling up available space with as much information as possible does not always give the best UX for the majority of users. GitHub made something more people focused than Google Code (which was designed for power users) and I believe that played a part in its success.

**Comment by andreasabel** [comment]
I am a power user, I am afraid.
