### ISSUE TITLE
GitHub Wiki

### ISSUE THREAD

**Issue by sharat** [holman/ama#737]
GitHub Wikis are as good as a GitHub repository but comes attached as part of a repo. Is there any rationale behind why we can't create a Wiki Independently? 

I feel, Wiki can be straight as a repo on sharing common Wiki/Documentation for products consists of multiple projects.

What are your thoughts?

**Comment by holman** [comment]
> Is there any rationale behind why we can't create a Wiki Independently?

In GitHub's mindset, the repository is the center of the universe.

> What are your thoughts?

I think the whole model should be rethought. GitHub's feature complete, though, so don't hold your breath.

**Comment by sharat** [comment]
How do you maintain the documentations? Is it over word files or wikis?

**Comment by holman** [comment]
If you're talking about regular documentation in a repository, a wiki or just a docs directory with Markdown files seems fine to me.

**Comment by sharat** [comment]
I was looking at more in terms of product documentation. Now GitHub is a complete product. There could several documentation required in terms of technical, compliance, features etc. How it is being managed?

**Comment by holman** [comment]
You'd have to ask them.

**Comment by sharat** [comment]
:+1: Thanks.

**Comment by dpen2000** [comment]
> GitHub's feature complete

Is this your view or GitHub's? I didn't think Products ever were finished
