### ISSUE TITLE
Custom Github Hoodies

### ISSUE THREAD

**Issue by afang** [holman/ama#743]
Please consider adding these to the official Github store: ![custom github hoodie](https://camo.githubusercontent.com/1fc336eb6ccd59961be3ad49cba780acce3497dc/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323732332f323036383830322f64336162633633382d386430662d313165332d393935322d3364396432663138386531612e6a7067)

Where did you get yours?

**Comment by holman** [comment]
Those are only available to GitHub employees, and that's a fate I wouldn't wish on anyone.
