### ISSUE TITLE
Any non-personal issues with GitHub?

### ISSUE THREAD

**Issue by ur0** [holman/ama#745]
I was about to apply to GitHub for an internship,  but I froze in my tracks after I saw this. (#743)

![default](https://cloud.githubusercontent.com/assets/7693065/10790986/562694e2-7dac-11e5-957a-3121f1c683e2.png)
Which is startling when you compare it to this.
![default](https://cloud.githubusercontent.com/assets/7693065/10791058/afd7e428-7dac-11e5-92a8-3f1212c9ff72.png)

Are there any non-personal issues that you have with GitHub? 

I'd entirely understand if you don't answer - but I *thought* GitHub would be a nice place to work at.

**Comment by holman** [comment]
Yes.

**Comment by ur0** [comment]
@holman, would you mind sharing? Except those in 'How GitHub no longer works?'. Cuz this is make or break for me, and the draft in Thunderbird is beginning to bother me. 

Sorry if I'm pissing you off.

**Comment by holman** [comment]
It's a culture incapable of shipping, and they treat their people horribly.

**Comment by ur0** [comment]
Thanks. That draft is in the bin now.

**Comment by afang** [comment]
@ur0 what is the reference in the photo?

**Comment by ur0** [comment]
@afang, the first one is from #743, and the second one is from @holman's [How GitHub (No Longer) works](http://zachholman.com/talk/how-github-no-longer-works/) talk.
