### ISSUE TITLE
What are some the essential travel apps you use?

### ISSUE THREAD

**Issue by sharat** [holman/ama#746]

**Comment by holman** [comment]
Mostly just TripIt, although that's a successful app in spite of everything the company's done. I still think it'd be dope if someone ended up trying to make a better TripIt.

I'll occasionally use Kayak to comparison shop prior to booking.

Other than that, just apps for whatever airline and hotel I'm using (which is usually Delta and SPG).

**Comment by sharat** [comment]
Thank you!
