### ISSUE TITLE
Web dev environment with gulp

### ISSUE THREAD

**Issue by Randall94** [holman/ama#749]
I am trying to set up a build / web development environment with gulp, with basic features for compiling SASS, browser-sync, auto prefixer etc. But after 2 days of consecutive experimenting, I am still failing at accomplishing this (seemingly) easy task, always getting some minor errors. 

Would you be able to help me out, if I provide more information ? (file structure, gulpfile.js code, commands etc.). I haven't found too many good tutorials on this topic and it might serve as a good reference for future users.

Thank you.

**Comment by holman** [comment]
Unfortunately might not be able to help you too much there- those aren't tools that I'm super familiar with. :\

**Comment by Randall94** [comment]
ah, ok. Thanks for the quick response anyway.

**Comment by mmcbride1007** [comment]
@Randall94 I've got [a repo](https://github.com/mmcbride1007/new-project) that I use as a template for starting new web dev projects, and it uses browserSync, LESS, and Gulp. I usually prefer LESS over SASS (my company uses LESS in our stack), but you could pretty easily swap out the gulp plugins for that. You might try [this gulp-sass plugin](https://github.com/dlmanning/gulp-sass) Hopefully this helps you. [Here's the gulpfile](https://github.com/mmcbride1007/new-project/blob/master/gulpfile.js) that I use there. If I can be of any help, feel free to reach out via an issue on that repo or via email (in my profile).

**Comment by Randall94** [comment]
@mmcbride1007 Perfect! Thanks. I have already got it working, but it always helps to explore a different approach. Will check it out.
