### ISSUE TITLE
What are some of the coolest pull requests you've seen on GitHub?

### ISSUE THREAD

**Issue by tonyyet** [holman/ama#750]
Recently I am teaching some of my friends who are non-techies the idea of git / GitHub and especially the idea pull request, because I found that to be at the heart of GitHub. 

Do you have any favorite examples of using pull requests in [creative ways](https://twitter.com/kcimc/status/659812732569567232/photo/1)?

**Comment by holman** [comment]
bunch of them in [this](http://mehulkar.com/github-hall-of-fame) I guess.

**Comment by ResidentMario** [comment]
Page appears to be down...

**Comment by sharat** [comment]
[Here it is](https://halls-of-fame.github.io/github/)

Source: https://github.com/halls-of-fame/github
