### ISSUE TITLE
Ruby, Rails and the future 

### ISSUE THREAD

**Issue by ur0** [holman/ama#755]
You've used Ruby/Rails for quite some time and have spoken extensively about its awesomeness. Indeed, Ruby is the single best language I've come across. 

But Internet today is so full of stuff like 'Ruby is dead', et cetra that it makes the programmer in me want to commit suicide.

What, in your opinion, is the future? Is it something without Ruby? Is it full of semicolons and parentheses and whatnot? Is the golden era gone? 

P.S: Dockbit, the company you're currently advising - do they use Rails?

**Comment by sharat** [comment]
@ur0 This covers it pretty well. 
#698

**Comment by holman** [comment]
Yeah, mostly what's in #698. I still love Ruby and think it's pretty dope.
