### ISSUE TITLE
Subject trend Year

### ISSUE THREAD

**Issue by juanespina** [holman/ama#757]
What do you think will be most talked about and studied this year, example API, Spec and tools.

**Comment by holman** [comment]
Not sure! I'm not really plugged into that type of stuff anymore, so my guess would probably be as good as yours. Some of the obvious stuff would be to say that Rust will get more traction, Go and Node will have some interesting things done/written in it, and there will be a new JavaScript framework come out that will change everything (and subsequently die before 2017).

**Comment by aungtun1988** [comment]
Support me

**Comment by aungtun1988** [comment]
Support me

**Comment by holman** [comment]
Witness me
