### ISSUE TITLE
Incorrect user name in the 'public activity' tab

### ISSUE THREAD

**Issue by pallix** [holman/ama#761]
The name of a username used in a mention in the comment of a PR and displayed in the 'public activity' tab of a user, is wrongly spelled. See images for a quick understanding.

[Public Activity](http://ibin.co/2VngXq3EGSLX)
[PR](http://ibin.co/2VngfxLY7ozG)

**Comment by holman** [comment]
Guessing things were edited after the fact? The news feed is a static snapshot in time rather than something that gets updated in real-time, iirc.

**Comment by pallix** [comment]
It's possible but that would surprise me as there is the completion and we only have one nickname beginning by the letter x on the team.

**Comment by pallix** [comment]
You were right - my coworked confirmed - sorry!
