### ISSUE TITLE
Roadmap transparency

### ISSUE THREAD

**Issue by dideler** [holman/ama#762]
Historically, GitHub has rarely pre-announced features or products intentionally; discussed a bit in #534.

[GitHub's response to the Dear GitHub letter](https://github.com/dear-github/dear-github/pull/115/files) hints that surprise and delight is still valued at the company

> We've also got a few surprises in store

But the company is also becoming more transparent

> Over the next few weeks we'll begin releasing a number of improvements to Issues
> [...]
> We're also going to kick off a few initiatives that will help give you more insight into what's on our radar.

Do you think this was the right response? Is GitHub heading in the right direction?

**Comment by holman** [comment]
Ha, not going to comment.

**Comment by dideler** [comment]
<img src="https://cloud.githubusercontent.com/assets/497458/13028752/815106de-d270-11e5-97c5-72cb32e7bda4.gif" width="400"/>
<img src="https://cloud.githubusercontent.com/assets/497458/13028753/858634ae-d270-11e5-83d4-8dcf73bf8658.gif" width="400"/>
