### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by iolloyd** [holman/ama#764]
I've recently been drawn to increasingly simplify our tool-set. What are your thought on using bog standard Makefiles for deployment?

**Comment by holman** [comment]
Really depends on what you're doing, really. I don't hate on using make for pretty simple stuff; it's certainly proven that it works for like, longer than a few decades. :)

Sometimes it's helpful to be able to plug directly into a language's features with the language itself, but really depends. At the end of the day the whole toolchain *should* be pretty simple.

**Comment by iolloyd** [comment]
Hey, thanks for the feedback. Eve Valkyrie will be somewhat indebted to you.
