### ISSUE TITLE
Do you even mailing list?

### ISSUE THREAD

**Issue by karan** [holman/ama#775]
Curious so I don't miss the posts and talks (especially videos).

**Comment by holman** [comment]
Nah. Thought about it, but haven't done anything about it yet.

Good ol' RSS exists, though! https://zachholman.com/atom.xml

I wonder if there's an RSS-to-email app somewhere. Has to be.

**Comment by karan** [comment]
IFTTT to the rescue!

**Comment by justincase** [comment]
I'm using https://blogtrottr.com for a couple of feeds.
