### ISSUE TITLE
What headphones/earphones do you use?

### ISSUE THREAD

**Issue by karan** [holman/ama#776]
My earphones broke and I'm looking for new ones now. What's your audio setup (from my "research" seems like you're content with the Apple ones)?

**Comment by holman** [comment]
Yeah; I usually just use Apple earbuds most of the time I'm listening to something. I like not feeling completely separate from the rest of the world.

When I'm DJing or when I can't use my KRKs at home for some reason (never), I use a pair of [HDJ-2000-W](http://www.amazon.com/Pioneer-HDJ-2000-W-Professional-In-Ear-Headphones/dp/B00A29ZND8)s.

**Comment by karan** [comment]
Wish Androids had a standard recommended earphones. Thanks. <3
