### ISSUE TITLE
Do you read books? Technical or otherwise . . . . . If yes, can you list a few? EOM

### ISSUE THREAD

**Issue by palerdot** [holman/ama#777]

**Comment by holman** [comment]
Sure, quite a bit. I don't have a list handy, but recent books I've read the last few months or so:

- Boomsville (currently)
- 11/22/63 (fucking terrible)
- The Corner
- Venture Deals
- Enemies of the FBI (fantastic)

**Comment by palerdot** [comment]
wow . . . . that was fast. Thanks.

**Comment by senk** [comment]
Do you mean this one? [Enemies: A History of the FBI](http://www.amazon.com/Enemies-History-FBI-Tim-Weiner/dp/0812979230/ref=sr_1_1?s=books&ie=UTF8&qid=1459680441&sr=1-1&keywords=Enemies+of+the+FBI
https://github.com/holman/ama/issues/777
http://www.amazon.com/Enemies-History-FBI-Tim-Weiner/dp/0812979230/ref=sr_1_1?s=books&ie=UTF8&qid=1459680441&sr=1-1&keywords=Enemies+of+the+FBI)?
