### ISSUE TITLE
Firing People

### ISSUE THREAD

**Issue by queuebit** [holman/ama#778]
> Thanks for reading my story.
> &mdash; https://zachholman.com/talk/firing-people

Thanks for sharing your story. Excited for what is _next_ for you.

---

In jest...

Did you see Ben _"fire"_ JoJo on _The Bachelor_ on Monday night? #spoiler 

She is now _"Next"_ for _The Bachelorette_.

**Comment by holman** [comment]
Haha, I don't watch The Bachelor(ette). Or much network TV at all at this point, ha. :) I'll have to take your word for it!
