### ISSUE TITLE
Is anyone else writing about firing people?

### ISSUE THREAD

**Issue by bcSwanson1987** [holman/ama#779]
I was reading your article on firing and I was wondering if you knew of anyone else who was writing from the management perspective- specifically about how to make sure that if I have a problem on my team, I'm giving them enough opportunity and clear enough directions in order to keep their job.

Really, I struggle in general with crafting goals and measuring against them, and I want to make sure that I'm giving all of my team a fair review, but it's doubly important if someone's job is on the line.

I've been following Rands in this area of how to be a  software manager, but I don't know of anyone else writes that much from the management side in software, and I want to make sure that I'm doing what I can to help people succeed (or at least keep their jobs).

**Comment by holman** [comment]
not really aware of any specific things I can point you toward, sorry
