### ISSUE TITLE
Process for modern development 

### ISSUE THREAD

**Issue by sharat** [holman/ama#780]
Hello,

What's the development process followed at companies like GitHub and some of your previous venture? Do you find Agile/Scrum are strictly followed?

**Comment by robi-y** [comment]
You might find these 2 papers interesting:
Facebook: [Development and Deployment at Facebook](https://research.facebook.com/publications/development-and-deployment-at-facebook/)
Google (ab it old): [Ssh! We are adding a process… ](http://www.agiliste.fr/wp-content/uploads/2012/09/REX-Transition-Agile-Google.pdf)

**Comment by holman** [comment]
GitHub never had any strict development process. I don't think highly of Agile or any real structured workflow.
