### ISSUE TITLE
Would you have been fired if you hadn't been burnt out / depressed?

### ISSUE THREAD

**Issue by ianchanning** [holman/ama#783]

**Comment by raypereda** [comment]
Based on his blog, I believe Zach was in need of a well deserved long break before he was fired. Feeling depressed only came after being fired.

**Comment by holman** [comment]
It's one of those questions that you can only guess at. I don't really know. With my situation it mostly came down to being stuck with a manager that didn't want to manage, so I'm not sure how you work around that. I'd been feeling pretty shitty for the last two or three years, though, tbh. GitHub's not a particularly supportive place to be if you're trying to work through some different mindsets. Guess that's not too far from the truth at most startups, though, so kind of par the course.

**Comment by ianchanning** [comment]
@raypereda - sorry I wasn't trying to imply that @holman's break wasn't deserved, quite the opposite,  it seems that (from the [Firing people][1] blog post) Github had a very limited amount of time it was willing to support an employee going through a rough patch.

@holman thanks, you're honesty around depression is more helpful than you'll ever possibly imagine. My cousin committed suicide through depression a few months back whilst studying at university. The more open about it we can be the better. I hope for a day when there's no difference between going for a heart / lung / little toe check up or going for a brain check up. 

I can see how companies don't want depressed people around as it can affect others, but it still seems a pretty shitty thing to do.

  [1]: https://zachholman.com/talk/firing-people

**Comment by holman** [comment]
> @holman thanks, you're honesty around depression is more helpful than you'll ever possibly imagine. My cousin committed suicide through depression a few months back whilst studying at university. The more open about it we can be the better. I hope for a day when there's no difference between going for a heart / lung / little toe check up or going for a brain check up.

Thanks, and I'm really sorry to hear that. :( I've been through similar experiences in the past and it's really, really horrible to deal with.

**Comment by endosynth** [comment]
@holman sounds like that was a really rough experience due to overwork... sounds very difficult to get through. I hope things are looking up for you now

**Comment by holman** [comment]
I'm the happiest I've been in years and years. 🎉

**Comment by raypereda** [comment]
:+1:
