### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by prodicus** [holman/ama#784]
I just wanted to say that your blog posts were a pleasure to read! (you do speak your mind) Stumbled upon them while reading hacker news. 

What did you major in while at CMU? How is your current gig going for you (Dockbit)? Any advice for young developers like me (undergrad)? :smile:

**Comment by holman** [comment]
Thanks!

I majored in Information Systems at CMU- although if I would do it again I definitely would have gone for Computer Science instead. But such is life.

I'm only advising at Dockbit (and two other startups at the moment), but they've been doing pretty great. Been fun watching them progress.

[I did a talk](https://zachholman.com/talk/if-only-i-knew-this-shit-in-college/) awhile back targeted at college students, although I feel like if I were to give it again it would be almost entirely different. Such is life, I suppose.

**Comment by prodicus** [comment]
What is your take on building things which give tangible output rather than the ability to solve some puzzles on whiteboard / paper?

**Comment by holman** [comment]
https://zachholman.com/posts/startup-interviewing-is-fucked/

**Comment by prodicus** [comment]
Thank you so much for your time :smile: 

I hope I get to attend one of your talks in person some time soon.And don't pay attention to the haters!

 Until next time then Zach

**Comment by palerdot** [comment]
Similar recent one
https://medium.com/@evnowandforever/f-you-i-quit-hiring-is-broken-bb8f3a48d324#.1zuz3c8lw

**Comment by RSully** [comment]
> I did a talk awhile back targeted at college students, although I feel like if I were to give it again it would be almost entirely different

Certainly welcome. Maybe a blog post?
