### ISSUE TITLE
Life is too short for bullshit

### ISSUE THREAD

**Issue by dideler** [holman/ama#785]
One of my favourite essays is PG's [_Life is Short_](http://paulgraham.com/vb.html).

> When I ask myself what I've found life is too short for, the word that pops into my head is "bullshit."

> Relentlessly prune bullshit, don't wait to do things that matter, and savor the time you have.

What's on your bullshit list?

**Comment by holman** [comment]
Eh, nothing right now. I'm dealing with a lot of bullshit at the moment, but nothing that can be pruned.
