### ISSUE TITLE
how do i convince you to be a mentor?

### ISSUE THREAD

**Issue by digideskio** [holman/ama#789]

**Comment by holman** [comment]
i'm not a mentor

**Comment by djch** [comment]
![smd](https://cloud.githubusercontent.com/assets/4392286/15413361/cb984fba-1e72-11e6-9074-2faa9b938c98.gif)

**Comment by digideskio** [comment]
one day, the kids are gonna grow up @djch

**Comment by sharat** [comment]
May be it's worth reading about [Ekalavya](https://en.wikipedia.org/wiki/Ekalavya)
