### ISSUE TITLE
Small typo in "the-new-10-year-vesting-schedule"

### ISSUE THREAD

**Issue by jaytaylor** [holman/ama#790]
Hi Zach,

I'm sure you're having a busy day, but I just wanted to let you know of a small typo in [this article](https://zachholman.com/posts/the-new-10-year-vesting-schedule):

"Hancuffed to Uber" when I think you meant "Han**d**cuffed to Uber".

*edit*

P.S. Please keep up the informative and fun-to-read blog posts :D

**Comment by holman** [comment]
So it is! Thanks for the catch- fixing.

I feel like half of my typos happen in the middle of a link or some sort of Markdown formatting; makes it easier to miss things like these, heh.
