### ISSUE TITLE
Small error in Evaluating Delusional Startups?

### ISSUE THREAD

**Issue by jamiewilson** [holman/ama#791]
Hey, maybe this is just me, but I kinda got hung up at [the beginning of this article](https://zachholman.com/posts/evaluating-delusional-startups). If it wasn't the opening sentence it probably wouldn't matter as much, but I think it might be better if you transpose "not" and "always":

> Okay, so they’re **not** always going to come at you like this.

Also, not sure if this was intentional, but this section in the third-to-last paragraph is a bit hard to read:

> …this bubble that will **certainly almost certainly okay maybe it’ll** pop again soon…

Anyway, I really enjoyed this post! Especially the part about hating the competition. I've never understood this and always try to help companies develop an appreciation and respect for others working on the same problems.

**Comment by holman** [comment]
Just some stylistic choices I went with there; it's what I wanted to go with. :)

> Anyway, I really enjoyed this post! Especially the part about hating the competition. I've never understood this and always try to help companies develop an appreciation and respect for others working on the same problems.

Cheers!

**Comment by jamiewilson** [comment]
✌🏼️
