### ISSUE TITLE
Go-to/favourite fonts and colour schemes

### ISSUE THREAD

**Issue by demoneaux** [holman/ama#793]
Hi! I'm interested to find out what are your favourite fonts/colour schemes that you use most of the time, especially for things like new sites/presentations.

I've looked through some of your talks (videos/slides), and they are really excellent. Any tips for the process of creating talks?

**Comment by holman** [comment]
I used to list all this stuff on my talks page, but ended up removing them a year or so ago. Such is life!

I've done a ton of different combinations over the years, but over the last 2-3 years specifically I've kind of standardized on specific combinations. In terms of fonts, I've mostly started using [Avenir Next](https://www.fonts.com/font/linotype/avenir-next) as kind of "my" font of choice the last few years — I've used it in many of my recent talks, and it's what my blawg is typeset in, too. It's pretty versatile in terms of weights and cases, and I like big, clear sans for talks.

In terms of colors... I think I've mostly just been simplifying more than anything else. Lately I've been using much fewer color combinations and doing simple black and white decks with a lot of photography. Once at that point, I'll effectively tint the whole thing to one specific color (or, in the case of [*Firing People*](https://zachholman.com/talk/firing-people), a gradient). Been kind of a fun new development, and if I were to do a new talk in the next year or two — probably not — it'd likely be an evolution along those lines.

> Any tips for the process of creating talks?

Yup. :) Check out [speaking.io](http://speaking.io). I've written a bunch there.
