### ISSUE TITLE
Why can't I link to the archive for my latest release?

### ISSUE THREAD

**Issue by dlenski** [holman/ama#794]
Github's [archive links](https://developer.github.com/v3/repos/contents/#get-archive-link) are totally awesome. I use them all the time for explaining to people how to install Python packages with `pip`, e.g.

```
pip install http://github.com/dlenski/python-project/archive/HEAD.zip # tip of default branch
pip install http://github.com/dlenski/python-project/archive/foobar.zip # tip of foobar branch
pip install http://github.com/dlenski/python-project/archive/v1.2.3.zip # tag v1.2.3
```

***However…*** what is slightly maddening to me is that there is no way to link to the zipball or tarball for the *most recent* tag or release for a project.

Oh sure, I can link to the [web page for the latest release](https://help.github.com/articles/linking-to-releases/#linking-to-the-latest-release) with `https://github.com/user/project/releases/latest` … but I can't generate a link that automatically points to an archive for that release :-1:.

Any idea why Github hasn't added this feature?

**Comment by holman** [comment]
don't give a shit

**Comment by davisonio** [comment]
https://github.com/isaacs/github
