### ISSUE TITLE
Thoughts on Day One 2?

### ISSUE THREAD

**Issue by nicatronTg** [holman/ama#795]
In #760, you were asked about Day One 2. Did you ever upgrade, and if so, are you liking it as much as you did Day One 1?

Cheers!

**Comment by holman** [comment]
Nope, not yet. I don't trust a small company with journal data (nothing against Day One in particular), so I wouldn't switch until it has private key encryption. I'm not really sure I'll ever switch at this point, tbh; that it's taking this long and that they launched without it kind of gives me pause as to how much they care about privacy and security. We'll see, though.
