### ISSUE TITLE
Found this awesome AMA and was offered to chat about a support position, opinion?

### ISSUE THREAD

**Issue by ProfessorKaos64** [holman/ama#796]
I received a message such as:

>Your interest in Linux and and troubleshooting caught my eye.  As you know, GitHub is an open-source platform that empowers a community of more than 14 million people to build software.  We are adding several Enterprise Support Agents to the growing remote support team. Someone like yourself - with a passion for technology - would be ideal.

It is in fact from a GitHub staffer. My Current job is at a hospital system, but with very few Linux-related jobs, I investigate any opportunity I can. Can you share some insight into what this kind of job is/entails?

Much appreciated,  
Mike

**Comment by j4s0nmchr1st0s** [comment]
Mike,

Send a private. For disconnecting jar files and release from the
'hospital'. Reply too my email and open two lines minimum for failsafe.

**Comment by holman** [comment]
Nah.

**Comment by j4s0nmchr1st0s** [comment]
Has your soul has been converted to Satan's puppet?

**Comment by ProfessorKaos64** [comment]
Ummmm ok then.

**Comment by j4s0nmchr1st0s** [comment]
It was addressed at Mike and you hive maggots oft respond for each other.

**Comment by jessephus** [comment]
I think @holman means that it isn't actually from anyone at GitHub.

**Comment by ProfessorKaos64** [comment]
Her full name and email address nat h her GitHub profile and organization. 

On August 19, 2016 5:55:07 PM EDT, Jesse Geraci <notifications@github.com> wrote:
>I think @holman means that it isn't actually from anyone at GitHub.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/holman/ama/issues/796#issuecomment-241145302

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by holman** [comment]
I just mean I don't care, ha. ✨💖

**Comment by jessephus** [comment]
Hahah. Fair enough.
