### ISSUE TITLE
The cost of open source projects hosting

### ISSUE THREAD

**Issue by sharat** [holman/ama#797]
GitHub's growth has been phenomenal with open source projects. They found a new home. Today  GitHub hosts some of the best open source projects and home for many. How the businesses tackle these issues? There are cases where certain [repos burn github servers](https://github.com/CocoaPods/CocoaPods/issues/4989). The ratio between the paid and free repos/users could be exponentially different. When we think in terms of business of a mature/feature complete product, how the cost will be balanced.

**Comment by holman** [comment]
It's interesting to think about. But I think overall it's not entirely *new*, really; the issue with CocoaPods is the same with virtually every service... every product has pathological edge cases. So I think it's just a matter of normal development when you build these types of business and services.
