### ISSUE TITLE
GitHub with bosses

### ISSUE THREAD

**Issue by sharat** [holman/ama#798]
It's quite interesting to read this article to understand the shift has happened at GitHub to better coordinate between departments and have bosses now.
[Why GitHub Finally Abandoned Its Bossless Workplace](http://www.bloomberg.com/news/articles/2016-09-06/why-github-finally-abandoned-its-bossless-workplace)

I quote Tom here 
> At GitHub we don’t have meetings. We don’t have set work hours or even work days. We don’t keep track of vacation or sick days. We don’t have managers or an org chart. We don’t have a dress code. We don’t have expense account audits or an HR department.

http://tom.preston-werner.com/2010/10/18/optimize-for-happiness.html

What's your take on the new move?

**Comment by holman** [comment]
It was a fluff piece that didn't offer anything.

People forget that the whole point of our approach was its flexibility; I don't think anyone really thought it would scale to 600 people. Something that works when you're a hundred that doesn't work when you're 500 doesn't mean the system is broken; it just means you're adaptable.

**Comment by sharat** [comment]
That absolutely right. I recall some of my early discussion here in terms of release process at GitHub and how it's structured. I was astonished by the number of releases you make everyday that could affect millions of people. Flexibility is the key when building something fast with with the small team which has transparency and trust each other.
