### ISSUE TITLE
Bug on commit order on PR view

### ISSUE THREAD

**Issue by ngbaoan** [holman/ama#805]
i found a bug on commit order on PR view, my view on terminal and branch are OK, see screenshots
![on_branch](https://cloud.githubusercontent.com/assets/1082890/20996620/1e802ace-bcff-11e6-8bd0-e0c509932370.png)
![on_pr](https://cloud.githubusercontent.com/assets/1082890/20996622/20db6068-bcff-11e6-8f15-d74d92ba64fd.png)
![on_terminal](https://cloud.githubusercontent.com/assets/1082890/20996626/247fce8e-bcff-11e6-9c38-114e26119899.png)
how to reproduce the bug:
- make a PR from branch A
- rebase A from branch B, push force branch A 
- look at commit order in PR

**Comment by dpen2000** [comment]
Zach doesn't work at GitHub anymore. Try https://github.com/contact
