### ISSUE TITLE
Projects and portfolios

### ISSUE THREAD

**Issue by hardikpandya** [holman/ama#806]
What projects and things are you working on at the moment? As a developer/designer, would you say maintaining a regularly updated portfolio is a good habit, provided it requires time and dedication as a trade-off?

**Comment by holman** [comment]
I'm working on something right now; nothing ready for an announcement yet, though.

Keeping a regularly updated portfolio is decent, particularly for designers. Keeping a regularly-updated skillset is better, though. :)
