### ISSUE TITLE
Are you in LinkedIn?

### ISSUE THREAD

**Issue by palerdot** [holman/ama#807]
I'm not in LinkedIn by choice. I feel there is a misguided notion among a few that if you do not have a LinkedIn account, then you are not a professional. That, coupled with how practically useless LinkedIn is for me as a programmer, and how people describe themselves on LinkedIn differently when they show completely different attitude and proficiency on their job, is keeping me away from LinkedIn.

I searched you on LinkedIn (in google of course) and could not find you. If you are not in LinkedIn, do you have a specific reason for that, or is it just you don't find it interesting but do not have any qualms regarding LinkedIn?

PS: I liked your post on getting fired mainly for the courage to come out open and just talk about it. I wish more people do this. 

All the best for your future works.

**Comment by holman** [comment]
> I searched you on LinkedIn (in google of course) and could not find you. If you are not in LinkedIn, do you have a specific reason for that, or is it just you don't find it interesting but do not have any qualms regarding LinkedIn?

Yeah; a few years ago I deleted my account.

It was one of those times where I got an email notification or something and then I finally stepped back and asked myself: is this bringing me any value? Any value whatsoever? I couldn't think of any, so I deleted it and haven't looked back.

I don't particularly hate LinkedIn or anything... I just don't see value in it, particularly in the programming field.

I've spent a long time thinking about this industry: I was at what would become Gild for two years or so, and then while at GitHub I basically had [GitHub Jobs](https://jobs.github.com) in the back of my mind the entire five years (as well as maintaining it for half of that).

I think there's an absurd amount of lucrative things you can do in this space, and LinkedIn isn't doing it. By "lucrative" I mean money, of course, but primarily I mean the things that *really have fucking impact*. Finding a job you love (or in many cases and industries, just any job) can have a huge, huge positive effect on your general well-being and health.

LinkedIn optimizes for recruiters, but if there's anything I've found it's that if you optimize for the job seeker, the recruiters are going to bend over backward to do anything you want, as long as you have qualified leads coming in.

If they made it easier for me to know 1) who of my friends are looking for a job (either actively or passively), and 2) who of my friends are actively hiring, and for what roles, then I would be much more interested to join up and try to help out my social group. Until then, though, LinkedIn just seems to increase the amount of recruiter emails you get.*

*\*not actually true given that I still get emails from recruiters stating "I saw you on LinkedIn!"*
