### ISSUE TITLE
Deploying Software, web-based environment control

### ISSUE THREAD

**Issue by jbjonesjr** [holman/ama#811]
@holman In https://zachholman.com/posts/deploying-software, you talk about different tools to manage environment locking.

> Another possibility that I've seen is to build web tooling around all of this. Slack has a custom internal app that provides a visual interface to deployment. [Pinterest]() has open sourced their web-based deployment system. You can take the idea of locking to many different forms; it just depends on what's most impactful for your team.

While it seems almost sac-religious these days to think about things not via ChatOps, that is still the case for many companies out there. Since this article was written, have you come across any additional examples of good web-based deployment tooling? I poked around to see if Slack had OSSed their stuff but didn't find anything.

Just curious if there is any new, exciting art for this space.

**Comment by holman** [comment]
Nothing particularly interesting, really (although admittedly I haven't really deployed anything of substance in a couple years).
