### ISSUE TITLE
Repository feature flags

### ISSUE THREAD

**Issue by parisk** [holman/ama#814]
Hey!

I am curious about how did you store the feature flags of repos in GitHub (e.g. enabled/disabled issues, wikis etc.).

Did you use the feature flags described in https://zachholman.com/posts/deploying-software, something similar, did you have a dedicated table for repo features, something else?

Cheers!

**Comment by holman** [comment]
I think those types of things aren't necessarily considered "feature flags"; in my mind, the characteristic of a feature flag is that they're temporary. They're best used when you're rolling out a new feature that you're testing for performance, usability, stability, etc. In the case of the repositories table, those are generally just boolean columns on the repository table itself; don't need to go with anything more complicated than that.
