### ISSUE TITLE
What are some more quotes that you remember from people you met?

### ISSUE THREAD

**Issue by Dorian** [holman/ama#816]
Inspired by https://zachholman.com/posts/three-quotes-from-early-githubbers

**Comment by holman** [comment]
Not really sure! Nothing particularly jumps out at me right now. Quotes are somewhat harder to remember sometimes. :)

The one thing I do remember is talking to Ron Johnson; I covered this in my [Firing People](https://zachholman.com/talk/firing-people) talk. Here's what he mentioned:

> There’s nothing wrong with moving along… regardless of whether it is self-driven or company-driven. Maybe we need new language… right now it’s either we resign or get fired.
>
> Maybe there’s a third concept which is “next”.
>
> Maybe we should simply recognize it’s time for next.
