### ISSUE TITLE
new repo page info - feature request

### ISSUE THREAD

**Issue by drbeco** [holman/ama#818]
Dear Holman, github team,

Do you know that page when we create a new repository completely empty? It gives you some commands to populate it:

---

### …or create a new repository on the command line
￼
> echo "# reponame" >> README.md
> git init
> git add README.md
> git commit -m "first commit"
> git remote add origin git@github.com:user/reponame.git
> git push -u origin master

### …or push an existing repository from the command line
￼
> git remote add origin git@github.com:user/reponame.git
> git push -u origin master

### …or import code from another repository

You can initialize this repository with code from a Subversion, Mercurial, or TFS project.

---

In the first section, I have lots of "first time users", students of mine, that mistakenly issue `git init` in their `$HOME` folder, adding a lot of files in the process (the worst case scenario, one of them added also his `.ssh` folder and private keys).

It wouldn't hurt to ask you guys to add just two more commands in the recipe, to make it clearer:

### …or create a new repository on the command line
￼
> mkdir reponame
> cd reponame
> echo "# reponame" >> README.md
> git init
> git add README.md
> git commit -m "first commit"
> git remote add origin git@github.com:user/reponame.git
> git push -u origin master

Please tell me if that is fair enough. 

My best.

@drbeco

**Comment by ur0** [comment]
@holman doesn't work for GitHub anymore - try contacting support@github.com.

**Comment by drbeco** [comment]
Thank you @ur0 , if not for you, this issue would be lost here forever.
