### ISSUE TITLE
Little Bug: Notifications dismissing and then move back in History

### ISSUE THREAD

**Issue by AdaLiszk** [holman/ama#819]
I don't know where I should report this, it's not a really big issue and it also shouldn't take too much time to solve it. Basicly it's a bug in History management (idk that GitHub using the `history.pushState()` or not), so when I dismiss all of my notifications and I hit the browser back button the page just simply refreshes.

I didn't looked the code actually, I assuming that the page either post the action and reload the page or sending the action trough Ajax then removing the unnecesseary content then adding a new item into the history. Both way it would be nice if in this case I could move back to my last page hitting only once the back button :smiley: 

Do I write this issue in a good place?

**Comment by holman** [comment]
support@github.com

**Comment by hakusaro** [comment]
@AdaLiszk Zach doesn't work at GitHub and hasn't since a couple years ago.

**Comment by AdaLiszk** [comment]
@hakusaro @holman I'm really sorry, I went to the support page but for some reason it showed that I could ask here :confused: Im really sorry to bother you with this.

**Comment by judoole** [comment]
Pretty funny that https://github.com/contact still today has all sorts of contactinfo directed to @holman and this repo.

**Comment by ferhatelmas** [comment]
It adapts to where you're coming from. Visit another repo and then see contact page, you'll realize difference.

**Comment by judoole** [comment]
@ferhatelmas Well that was quite embarrassing :smile:

**Comment by judoole** [comment]
@ferhatelmas Seem like it is stored in a cookie and shows the last repository you visited. For example visit a repo, go to github.com, then github.com/contact, and it will respond with the last repository you visited. Perhaps not the most intuitive experience.

Anyways, searching for "bug github" results in #152 showing as the top result in a google search.  Could perhaps explain why so people keep asking Github-related issues here.

**Comment by ferhatelmas** [comment]
@judoole Makes sense :+1:
