### ISSUE TITLE
Opened 15 other issues in 6 repositories section of profile not linked

### ISSUE THREAD

**Issue by jidanni** [holman/ama#825]
Visit https://github.com/jidanni
See where it says ```Opened 15 other issues in 6 repositories```?
Well that whole section cannot be clicked on. None of the items are hyperlinked.

Sorry for reporting this here but I have had bad experience with reporting via email with some organizations.

**Comment by hakusaro** [comment]
Holman doesn’t work for GitHub anymore. You have to go through GitHub
support. Sorry.

https://github.com/contact

**Comment by holman** [comment]
Reporting it via an issue to a rando who left years ago ain’t much better. ;)

**Comment by jidanni** [comment]
OK I wrote staff and they fixed it.
