### ISSUE TITLE
What kind of music do you listen to?

### ISSUE THREAD

**Issue by kiriakosv** [holman/ama#829]

**Comment by holman** [comment]
Lots of things!

I kinda stopped scrobbling earlier this year, but [my last.fm](https://www.last.fm/user/zachholman/library/artists) is still fairly accurate. I kind of am a picky listener, but bounce between genres a fair bit. The last 5-7 years or so I've been getting more into electronic (typified by Justice and other Ed Banger artists), but I'm also big into hip hop, jazz, and various singer/songwriter types.

Mostly I think music is dope, and I think everyone should be listening to more of it.
