### ISSUE TITLE
Managing dotfiles

### ISSUE THREAD

**Issue by johnzimmerman** [holman/ama#831]
If you were starting your dotfiles from scratch , would you manage them the same way or go with [this implementation](https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/) mentioned in Atlassian’s blog?

**Comment by holman** [comment]
Yeah that looks pretty neat; haven't seen it mentioned before.

I think if I were to do it again, I'd probably use something like oh-my-zsh and start from there, but my own dotfiles probably is pretty nice too, ha. :)
