### ISSUE TITLE
Twitter: 140 characters = efficiency‽

### ISSUE THREAD

**Issue by sloanlance** [holman/ama#834]
Hi, @holman.

I have a problem with GitHub to report…

Just kidding!

So, you wrote "140 characters makes everyone more efficient".  Is that really true?  Or is it just such a small amount of space that everyone must write very poorly to say all they want?  Either that, or they have to spend a lot of time breaking their statements into multiple small messages.

Isn't it time Twitter gave us all a gift in the form of an upgrade from 140 characters to… I don't know, some number of characters,  𝑛 < ∞?

FWIW, Twitter's limited space has helped me cultivate a vocabulary of space-saving characters like "‽", "…", and "≠".

**Comment by sharat** [comment]
Have a look at this tweet.

https://twitter.com/caitlin__kelly/status/912795950476857344
![dkrm0pdxuaij95- jpg-large](https://user-images.githubusercontent.com/405971/32312881-06aca2ea-bfc6-11e7-8a9b-d3c289ac913e.jpeg)

140 characters put lot of restrictions but often we can learn to optimise how to express our ideas. There are languages like 

Twitter throws another problem in terms of limitations/abilities of languages in their [biog post](https://blog.twitter.com/official/en_us/topics/product/2017/Giving-you-more-characters-to-express-yourself.html)

> Interestingly, this isn't a problem everywhere people Tweet. For example, when I (Aliza) Tweet in English, I quickly run into the 140 character limit and have to edit my Tweet down so it fits. Sometimes, I have to remove a word that conveys an important meaning or emotion, or I don’t send my Tweet at all. But when Iku Tweets in Japanese, he doesn’t have the same problem. He finishes sharing his thought and still has room to spare. This is because in languages like Japanese, Korean, and Chinese you can convey about double the amount of information in one character as you can in many other languages, like English, Spanish, Portuguese, or French.

Certainly 140 characters made think different but there are many times we had to make use of using "1/2" at end of tweets or make use of reply (thanks for the conversation interface) feature to convey something in a row.

**Comment by holman** [comment]
Hah, mostly was being selfish with that remark; 140 characters makes *me* efficient. It's way easier to respond to a tweet than a long rambling email. That in turn makes the whole process a lot quicker for everyone.

Beyond that, though, constraints are great. They make you become more forceful, get you quicker to the point you're trying to make. Less is more.

**Comment by djch** [comment]
I can't be the only one who finds themselves involuntarily skimming right past 280 character tweets. 140 seems to be in some cognitive sweet spot (for me).

**Comment by sharat** [comment]
Twitter already made me lazy to read anything lengthier. It is useful sometimes to not waste time. especially long-term users already have the mindset of optimized tweets but still had to go with multiple tweets to convey something. I rarely see those 1/2 tweets these days.
