### ISSUE TITLE
What are your travel hacks?

### ISSUE THREAD

**Issue by sharat** [holman/ama#837]
What are your travel hacks? Favorites apps, and other tips etc.

**Comment by holman** [comment]
Don't have as much as I probably should. A few things come to mind:

- [Tripit](https://tripit.com), synced to my calendar via [During](https://during.com). Tripit is kind of a bad product these days; a ton of things could be done and improved, but it's still the best (only?) product at what it does. So yeah, that manages all my travels.
- I hit up [/r/churning](https://reddit.com/r/churning) every now and then. I don't "churn" (sign up for credit cards purely for the signup bonuses), but it's helpful to get a lay of the land as to what credit cards might fuel better points and miles to eventually pay for flights for free.
- My buddy runs [Thrifty Traveler](https://thriftytraveler.com), and their [Premium](https://thriftytraveler.com/premium/) newsletter is a nice daily email of mistake fares, cheap fares, etc. That has been super helpful when I have a more open-ended travel idea (as opposed to conference travel, which is tied to specific days I need to be there).
- I use [Foursquare](https://foursquare) and [Swarm](https://www.swarmapp.com) religiously while traveling. It's super helpful to be in a city and pull up a map of places my friends have been to or places I've been to years ago. Many times while traveling you're not looking for *the best* option necessarily; just one that doesn't waste your time.
- Learning your main airline's fine print can be helpful. There's a lot of junk most people don't use (or know about). I made it home from Colorado last month twelve hours early so I could get back in time enough to catch a US Women's National Team game in San Jose. It woulda been cost prohibitive for flight changes normally, but same day confirmed on Delta made it free.
