### ISSUE TITLE
other than an AI to code for you, what's a tool or plugin for work that you wish existed but you're too lazy to create?

### ISSUE THREAD

**Issue by GhettoSanta** [holman/ama#842]
or a tool that's now unmaintained and you wish would be picked up again

and what's something you wish all crap/new/mediocre developers would start or stop doing?

**Comment by holman** [comment]
Something to fix fundraising. The VC market is totally fucked.

Tech-wise... a better testing solution (or really any testing solution at all) for Apollo apps.

Nothing really I'd hate on new developers for; everything is a journey. I think in general people should shutter REST apps, though, and switch entirely to GraphQL. I'm never writing another line of REST again.
