### ISSUE TITLE
What do you think of Microsoft acquisition of Github?

### ISSUE THREAD

**Issue by palerdot** [holman/ama#844]
Also, please share some details on your current git hosting for your personal/commercial projects. Do you actively use github, migrated to gitlab?

Thanks for your time.

**Comment by holman** [comment]
I think it’s great.

I use GitHub and GitLab.

**Comment by hakusaro** [comment]
Bitbucket?

**Comment by holman** [comment]
From time to time! I’m not a hater. (I own stock in all three. I’m long on computers; I think computers will be here for a bit.)
