### ISSUE TITLE
HTML to Image Convertion connections missing between Images

### ISSUE THREAD

**Issue by RajaKorada** [holman/ama#846]
Hi Team,

In my project i am using **html2Canvas plugin**  for html to image conversion but in the image connections are missing. pf below image for more information about my issue
![connectionissue](https://user-images.githubusercontent.com/25481578/42406860-f5db28b8-81cd-11e8-974d-3ba21ec555fd.png)

but i want result like below image :
![original](https://user-images.githubusercontent.com/25481578/42406869-37c6b382-81ce-11e8-96cf-faac429010a7.png)

please help me..

Regards,
Rajednra.K

**Comment by holman** [comment]
This isn't the right place for this; sorry! Can't help you with this, unfortunately.
