### ISSUE TITLE
Do you still use Jekyll as blogging platform?

### ISSUE THREAD

**Issue by spirosag** [holman/ama#847]
Are you still using Github pages and Jekyll as your blogging platform? I'm asking because I noticed some new pages in your talks section with custom design. Is this done by hand? What is your opinion on github pages with  jekyll? Would you suggest it as a platform or would you suggest something else?
I'm asking because I want to start a blog/portfolio type of website.

**Comment by holman** [comment]
Yup. It's all Jekyll + Pages, just normal HTML + CSS work.

> What is your opinion on github pages with jekyll? Would you suggest it as a platform or would you suggest something else?

I still really like it; handles pretty much everything that I'd need for a standard static site. No real complaints, and it's pretty boring and straightforward, which is all I ask for in life these days.
