### ISSUE TITLE
Support email is no longer used

### ISSUE THREAD

**Issue by jcollum** [holman/ama#887]
https://github.com/holman/ama/issues/152 

However when I emailed them I was told that they no longer use that: 

> Hi there,
> 
> We now require that new support requests be created using our Support website:
> 
> https://support.github.com
> 
> Please use this website to search through resources that may help you find the solutions you are looking for or connect with our GitHub experts.
> 
> Thank you,
> GitHub Support

NBD but your issue is one of the first google hits, so it would be helpful if you updated your comment in that issue.

**Comment by holman** [comment]
¯\_(ツ)_/¯

**Comment by jcollum** [comment]
I don't think "shrug" is an appropriate response here. Please just update the comment that I pointed out so the next person to do what I did won't have to go through the same process just to realize that the info in your comment is outdated.
